n = input('Digite algo: ')
print('O numero primitivo desse valor é ',type(n))
print('É alfanumerico? ',n.isalnum())
print('É um numeral? ',n.isnumeric())
print('É letra? ',n.isalpha())
print('É um digito?', n.isdigit())
print('É um decimal? ',n.isdecimal())
print('Está em Minusculo? ',n.islower())
print('Está em Maiusculo? ',n.isupper())
print('Só tem espaço? ', n.isspace())
print('Está capitalizada? ', n.istitle())
