n = int(input('Digite um numero: '))
#n1 = n*1
#n2 = n*2
#n3 = n*3
#n4 = n*4
#n5 = n*5
#n6 = n*6
#n7 = n*7
#n8 = n*8
#n9 = n*9
#n0 = n*10
print('A tabuada desse numero é:')
print('='*12)
print('{} x  1 = {}'.format(n, n*1))
print('{} x  2 = {}'.format(n, n*2))
print('{} x  3 = {}'.format(n, n*3))
print('{} x  4 = {}'.format(n, n*4))
print('{} x  5 = {}'.format(n, n*5))
print('{} x  6 = {}'.format(n, n*6))
print('{} x  7 = {}'.format(n, n*7))
print('{} x  8 = {}'.format(n, n*8))
print('{} x  9 = {}'.format(n, n*9))
print('{} x 10 = {}'.format(n, n*10))
print('='*12)
